// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkFlzRT4PTztKdVDZLHzl0HApn7HEE3cs',
    appId: '1:850032071795:web:46dc503e1a5a34c7048606',
    messagingSenderId: '850032071795',
    projectId: 'clone-puretrovey',
    authDomain: 'clone-puretrovey.firebaseapp.com',
    databaseURL: 'https://clone-puretrovey-default-rtdb.firebaseio.com',
    storageBucket: 'clone-puretrovey.firebasestorage.app',
    measurementId: 'G-N0BSVQL52R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkFlzRT4PTztKdVDZLHzl0HApn7HEE3cs',
    appId: '1:850032071795:android:46dc503e1a5a34c7048606',
    messagingSenderId: '850032071795',
    projectId: 'clone-puretrovey',
    authDomain: 'clone-puretrovey.firebaseapp.com',
    databaseURL: 'https://clone-puretrovey-default-rtdb.firebaseio.com',
    storageBucket: 'clone-puretrovey.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkFlzRT4PTztKdVDZLHzl0HApn7HEE3cs',
    appId: '1:850032071795:ios:46dc503e1a5a34c7048606',
    messagingSenderId: '850032071795',
    projectId: 'clone-puretrovey',
    authDomain: 'clone-puretrovey.firebaseapp.com',
    databaseURL: 'https://clone-puretrovey-default-rtdb.firebaseio.com',
    storageBucket: 'clone-puretrovey.firebasestorage.app',
    iosBundleId: 'com.example.peertask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAkFlzRT4PTztKdVDZLHzl0HApn7HEE3cs',
    appId: '1:850032071795:macos:46dc503e1a5a34c7048606',
    messagingSenderId: '850032071795',
    projectId: 'clone-puretrovey',
    authDomain: 'clone-puretrovey.firebaseapp.com',
    databaseURL: 'https://clone-puretrovey-default-rtdb.firebaseio.com',
    storageBucket: 'clone-puretrovey.firebasestorage.app',
    iosBundleId: 'com.example.peertask',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAkFlzRT4PTztKdVDZLHzl0HApn7HEE3cs',
    appId: '1:850032071795:web:46dc503e1a5a34c7048606',
    messagingSenderId: '850032071795',
    projectId: 'clone-puretrovey',
    authDomain: 'clone-puretrovey.firebaseapp.com',
    databaseURL: 'https://clone-puretrovey-default-rtdb.firebaseio.com',
    storageBucket: 'clone-puretrovey.firebasestorage.app',
    measurementId: 'G-N0BSVQL52R',
  );
}